exports.DATE_FORMAT = "YY-MM-DD HH:mm"
exports.JPEG_EXTENSION = ".jpg"
exports.S_THUMB_POSTFIX = "_S_THUMB"
exports.M_THUMB_POSTFIX = "_M_THUMB"
exports.L_THUMB_POSTFIX = "_L_THUMB"
exports.PRODUCTION_DOMAIN = "streetzone.pl"
