export const SIGN_UP = "/rejestracja"
export const SIGN_IN = "/login"
export const HOME = "/"
export const PASSWORD_FORGET = "/pw-reset"
export const ACCOUNT_BASE = "/profil/:id"
export const ACCOUNT_ITEMS = ACCOUNT_BASE + "/przedmioty"
export const ACCOUNT_SETTINGS = ACCOUNT_BASE + "/edytuj"
export const ACCOUNT_FEEDBACK = ACCOUNT_BASE + "/opinie"
export const ACCOUNT_INFO = ACCOUNT_BASE + "/info"
export const ACCOUNT_LIKED = ACCOUNT_BASE + "/zapisane"
export const ACCOUNT_FOLLOWING = ACCOUNT_BASE + "/obserwowane"
export const DESIGNER = "/marki/:id"
export const ITEM_DETAILS = "/i/:id"
export const NEW_ITEM = "/nowy"
export const DELETE_ITEM = "/usun/:id"
export const EDIT_ITEM = "/e/:id"
export const BLOG_HOME = "/blog"
export const BLOG_POST = "/blog/:id"
export const FAQ = "/faq"
export const PRIVACY_POLICY = "/polityka-prywatnosci"
export const ABOUT = "/o-nas"
export const CONTACT = "/kontakt"
export const TERMS = "/regulamin"

// External
// TODO: create social media pages and add addresses
export const FACEBOOK_PROFILE = ""
export const TWITTER_PROFILE = ""
export const INSTAGRAM_PROFILE = ""
