import { library } from "@fortawesome/fontawesome-svg-core"
import {
	faSpinner,
	faSync,
	faUser,
	faPlus,
	faUserCircle,
	faAngleRight,
	faAngleDoubleRight,
	faAngleLeft,
	faAngleDoubleLeft,
	faTimes,
	faExclamation,
	faBars,
	faUpload,
	faTrash,
	faCalendar,
	faCaretLeft,
	faFilter,
	faSort,
	faCaretDown,
	faCaretUp,
	faAngleUp,
	faAngleDown,
	faHeart,
	faSyncAlt,
	faSearch,
	faImage,
	faEllipsisH,
	faCheck,
	faInfoCircle,
	faFlag,
	faPhone
} from "@fortawesome/free-solid-svg-icons"
import {
	faHeart as farHeart,
	faEnvelope as farEnvelope /* , faSquare, faCheckSquare */
} from "@fortawesome/free-regular-svg-icons"
import { fab } from "@fortawesome/free-brands-svg-icons"

library.add(
	faSpinner,
	faSync,
	faUser,
	faPlus,
	faUserCircle,
	// faSquare,
	// faCheckSquare,
	faAngleRight,
	faAngleDoubleRight,
	faAngleLeft,
	faAngleDoubleLeft,
	faTimes,
	faExclamation,
	faBars,
	faTrash,
	faUpload,
	faCalendar,
	fab,
	faCaretLeft,
	faFilter,
	faSort,
	faCaretDown,
	faCaretUp,
	faAngleUp,
	faAngleDown,
	faHeart,
	farHeart,
	farEnvelope,
	faSyncAlt,
	faSearch,
	faImage,
	faEllipsisH,
	faCheck,
	faInfoCircle,
	faFlag,
	faPhone
)
